sudo: required

language: node_js
node_js:
    - stable

services:
    - docker

before_install:
    # install heroku CLI
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    # login to docker registries (dockerhub + heroku)
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - echo "$HEROKU_PASSWORD" | docker login --username "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
    # install deps
    - yarn install

script:
    - yarn test
    - yarn build
    # build docker images
    - docker build -t mrexplorers/mr-explorer-orchestrator .
    - docker tag mrexplorers/mr-explorer-orchestrator registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
    provider: script
    script:
        # push to docker hub
        docker push mrexplorers/mr-explorer-orchestrator;
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    branch: master
